VentanillaVirtual.Web/Controllers/SolicitudController.cs
using System;
using System.Web;
using System.Web.Mvc;
using VentanillaVirtual.Web.Models;
using VentanillaVirtual.LogicaNegocio;
using VentanillaVirtual.Entidad;
using System.Data;
using System.Collections.Generic;
using Utils;
using System.Linq;
using System.IO;
using CrystalDecisions.CrystalReports.Engine;

namespace VentanillaVirtual.Web.Controllers
{
    [CheckAuthorization]
    public class SolicitudController : Controller
    {
        // GET: Solicitud
        public ActionResult Index()
        {
            ////indicador de Menu
            ViewBag.OpPadre = "Bandeja";
            ViewBag.OpHijo01 = "Solicitudes";
            ViewBag.OpHijo02 = "";

            ViewBag.vbFECHA = System.DateTime.Today.ToShortDateString();
            ViewData["iIdRegi"] = Session["SIdUsuario"];
            return View();
        }


   
        [HttpPost]
        public ActionResult BuscarSolicitud(int strCodigo)
        {


            //jQuery DataTables Param
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            //Find paging info
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            //Find order columns info
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();


            //var strTipoBusq = Request.Form.GetValues("columns[0][search][value]").FirstOrDefault();
            //var strValorBusq = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();


            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt16(start) : 0;
            int recordsTotal = 0;


            List<SOLICITUD_Be> list = new List<SOLICITUD_Be>();

            list = fbd_BuscarSolicitud(strCodigo);

            recordsTotal = list.Count();
            var data = list.Skip(skip).Take(pageSize).ToList();

            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data }, JsonRequestBehavior.AllowGet);

        }

        private static List<SOLICITUD_Be> fbd_BuscarSolicitud(int strCodigo)
        {

            List<SOLICITUD_Be> lsGenerado = null;
            try
            {

                SOLICITUD_Br SOLICITUDBr = new SOLICITUD_Br();
                SOLICITUD_Be SOLICITUDBe = new SOLICITUD_Be();

                SOLICITUDBe.IDREGISTRO = strCodigo;

                lsGenerado = SOLICITUDBr.Ps_SOLICITUD(SOLICITUDBe);

                
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

            return lsGenerado;
        }


        [HttpPost]
        public ActionResult EliminarSolicitud(string StrSolicitud)
        {

            try
            {
                //OPC=1 REGISTRAR //OPC=2 EDITAR //OPC=3 ELIMINAR

                RESPUESTA_Be RESPUESTABe = new RESPUESTA_Be();

                SOLICITUD_Be SOLICITUDBe = new SOLICITUD_Be();
                SOLICITUDBe.OPC = 0;
                SOLICITUDBe.IDSOLICITUD = (StrSolicitud != "") ? Convert.ToInt32(StrSolicitud.ToString().Trim()) : 0;
                SOLICITUDBe.IDREGISTRO = 0;
                SOLICITUDBe.TXTASUNTO = "";
                SOLICITUDBe.TXTOBSERVACION = "";
                SOLICITUDBe.TXTFOLIOS = "";
                SOLICITUDBe.IDTIPOSOLICITUD = 2;
                //SOLICITUDBe.TIPO_P_inCODTIP = (StrHCodTipdoc != "") ? Convert.ToInt32(StrHCodTipdoc.ToString().Trim()) : 0;
                SOLICITUDBe.IDTUPA = 0;
                SOLICITUDBe.ESTADO = "0";
                RESPUESTABe.proValor = new SOLICITUD_Br().Pid_SOLICITUD(SOLICITUDBe);

                if (RESPUESTABe.proValor != "0")
                {
                    RESPUESTABe.proMensaje = "Se Registro Correctamente la solicitud.";
                }
                else
                {
                    RESPUESTABe.proMensaje = "Error no se registro la solicitud, Vuelve a intentar.";
                }

                return Json(RESPUESTABe, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                throw;
            }


        }





        [HttpPost]
        public ActionResult BuscarAdjArchivo(string IdSolicitud)
        {

            int recordsTotal = 0;
            List<ARCHIVOADJ_Be> list = new List<ARCHIVOADJ_Be>();
            ARCHIVOADJ_Be ARCHIVOADJBe = new ARCHIVOADJ_Be();
            ARCHIVOADJ_Br ARCHIVOADJBr = new ARCHIVOADJ_Br();

            list = (List<ARCHIVOADJ_Be>)ARCHIVOADJBr.Ps_ARCHIVOADJ(IdSolicitud);
            recordsTotal = list.Count();

            var start = Convert.ToInt16(Request.Form.GetValues("start").FirstOrDefault());
            var length = Convert.ToInt32(Request.Form.GetValues("length").FirstOrDefault());

            var draw = Request.Form.GetValues("draw").FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt16(start) : 0;


            var data = list.Skip(skip).Take(pageSize).ToList();

            return Json(new
            {
                draw = draw,
                recordsFiltered = recordsTotal,
                recordsTotal = recordsTotal,
                data = data
            }, JsonRequestBehavior.AllowGet);


        }



        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult AdjArchivo()
        {

            ARCHIVOADJ_Be ARCHIVOADJBe = new ARCHIVOADJ_Be();

            ARCHIVOADJBe.TIPOPROCESO = Request["vTipo"].ToString().Trim();
            ARCHIVOADJBe.IDSOLICITUD = Convert.ToInt32(Request["vIdSolicitud"].ToString().Trim());
            ARCHIVOADJBe.DESCARCHIVO = Request["vDescrip"].ToString().Trim();
            
            var pic = System.Web.HttpContext.Current.Request.Files["MFiles"];
            if (pic != null)
            {
                if (pic.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(pic.FileName);
                    // var _ext = Path.GetExtension(pic.FileName);
                    string adjunto = DateTime.Now.ToString("yyyyMMddHHmmss") + "_" + fileName;

                    string CarpetaMes = DateTime.Now.Month.ToString();
                    string CarpetaAnio = DateTime.Now.Year.ToString();
                    //string CarpetaBase =  + "FotoPapeleta\\Multa\\";
                    string CarpetaBase = Server.MapPath("~/File_Doc/Documento/");
                    string BusCarpeta = CarpetaBase + CarpetaAnio;
                    bool exists = Directory.Exists(BusCarpeta);
                    if (!exists)
                    {
                       Directory.CreateDirectory(BusCarpeta);
                    }

                    BusCarpeta = CarpetaBase + CarpetaAnio + "\\" + CarpetaMes;
                    exists = Directory.Exists(BusCarpeta);
                    if (!exists)
                    {
                        Directory.CreateDirectory(BusCarpeta);
                    }

                    var _comPath = CarpetaBase + CarpetaAnio + "\\" + CarpetaMes + "\\" + adjunto;

                    pic.SaveAs(_comPath.ToString());
                    ARCHIVOADJBe.TXTURLARCHIVO = "../File_Doc/Documento/" + CarpetaAnio + "/" + CarpetaMes + '/' + adjunto;

                }
                else
                {
                    ARCHIVOADJBe.TXTURLARCHIVO = "";
                }
            }
            else
            {
                ARCHIVOADJBe.TXTURLARCHIVO = "";
            }

            string lstNUMDOCUMENTO = fbd_ArchivoAdjPid(ARCHIVOADJBe);
            return Json(lstNUMDOCUMENTO, JsonRequestBehavior.AllowGet);

        }

        private string fbd_ArchivoAdjPid(ARCHIVOADJ_Be ARCHIVOADJBe)
        {

            return new ARCHIVOADJ_Br().Pid_ARCHIVOADJ(ARCHIVOADJBe);

        }


        [HttpPost]
        public ActionResult EliminarAdjArchivo(string strIdArc)
        {

            Int32 iCod = Convert.ToInt32(strIdArc.ToString());

            ARCHIVOADJ_Be ARCHIVOADJBe = new ARCHIVOADJ_Be();

            ARCHIVOADJBe.CODARCHIVO = iCod;
            ARCHIVOADJBe.DESCARCHIVO = "";
            ARCHIVOADJBe.TXTIP = "";
            ARCHIVOADJBe.TIPOPROCESO = "0";

            string iResultado = fbd_ArchivoAdjPid(ARCHIVOADJBe);

            return Json(iResultado, JsonRequestBehavior.AllowGet);

        }



        [HttpPost]
        public ActionResult EnviarSolicitud(string StrSolicitud)
        {

            try
            {

                //OPC=1 REGISTRAR //OPC=2 EDITAR //OPC=3 ELIMINAR

                RESPUESTA_Be RESPUESTABe = new RESPUESTA_Be();

                SOLICITUD_Be SOLICITUDBe = new SOLICITUD_Be();
                SOLICITUDBe.OPC = 2;
                SOLICITUDBe.IDSOLICITUD = (StrSolicitud != "") ? Convert.ToInt32(StrSolicitud.ToString().Trim()) : 0;
                SOLICITUDBe.IDREGISTRO = 0;
                SOLICITUDBe.TXTASUNTO = "";
                SOLICITUDBe.TXTOBSERVACION = "";
                SOLICITUDBe.TXTFOLIOS = "";
                SOLICITUDBe.IDTIPOSOLICITUD = 2;
                //SOLICITUDBe.TIPO_P_inCODTIP = (StrHCodTipdoc != "") ? Convert.ToInt32(StrHCodTipdoc.ToString().Trim()) : 0;
                SOLICITUDBe.IDTUPA = 0;
                //SOLICITUDBe.ESTADO = "0";
                RESPUESTABe.proValor = new SOLICITUD_Br().Pid_SOLICITUD(SOLICITUDBe);

                if (RESPUESTABe.proValor != "0")
                {
                    RESPUESTABe.proMensaje = "Se Envio Correctamente la solicitud.";
                }
                else
                {
                    RESPUESTABe.proMensaje = "Error no se envio la solicitud, Vuelve a intentar.";
                }

VentanillaVirtual.Web/Views/Expediente/Index.cshtml
@{
    ViewBag.Title = "Expediente";
    Layout = "~/Views/Shared/_Plantilla01.cshtml";
}


<div id="content">
    <div class="container">

        @Html.Partial("_MenuP02")

        <div class="row" id="Div01" style="display:none;">

            <div class="col-md-12">
                <div class="widget box">

                    <div class="widget-header">
                        <h4>
                            <i class="icon-file-text-alt"></i>
                            Registrar Expediente (Tupa)
                        </h4>
                    </div>

                    <div class="widget-content">

                        <form name="formulario" id="formulario">


                            <div class="widget-content">

                                @*<div class="alert alert-success">
                                    <i class="fa fa-check-circle"></i>
                                    <strong>Nota:</strong> Las cartas fianza y cualquier otro  título valor que sean  presentados por la Ventanilla Virtual, deberán ser entregadas en original en la Plataforma de Atención al Ciudadano del MINEM en un plazo no mayor a 2 días hábiles, indicando el número de expediente con el que se registró en la Ventanilla Virtual.
                                </div>*@

                                <input type="hidden" id="HCodRegi" name="HCodRegi" class="form-control" autocomplete="off" value="@ViewData["VIdRegi"]">

                                @Html.Partial("_Remitente")

                             </div>



                            <div class="widget-content">
                                <div class="panel panel-default">

                                    <div class="panel-heading title">
                                        <span class="glyphicon glyphicon-file styleicon"></span>
                                        <j2>Datos del Documento</j2>
                                    </div>

                                    <div class="panel-body">

                                        <div class="form-group row">
                                            <label for="staticAsunto" class="col-sm-2 col-form-label">Asunto(*) :</label>
                                            <div class="col-sm-10">
                                                <textarea class="form-control rounded-0" id="txtSolicitud" name="txtSolicitud" cols="10" data-val="true" placeholder="Ingrese aquí la descripción del asunto del Expediente (Mínimo 20 y máximo 250 caracteres)." rows="2" maxlength="250"></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="stacticObs" class="col-sm-2 col-form-label">Observación:</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" id="txtObs" name="txtObs" placeholder="Ingrese aquí sus observaciones (No es obligatorio)." maxlength="250" />
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="stacticObs" class="col-sm-2 col-form-label">Nro Folios(*) :</label>
                                            <div class="col-sm-2">
                                                <input type="text" class="form-control" id="txtFolio" name="txtFolio" OnKeyPress="return solonumeros(event)" />
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>



                            <div class="widget-content">
                                <div class="panel panel-default">

                                    <div class="panel-heading title">
                                        <span class="glyphicon glyphicon-book styleicon"></span>
                                        <j2>Datos Procedimiento Tupa</j2>
                                    </div>

                                    <div class="panel-body">
                                        <div class="form-group row">
                                            <label for="staticAsunto" class="col-sm-2 col-form-label">Tupa :</label>
                                            <div class="col-sm-8">
                                                <textarea class="form-control rounded-0" id="txtTupa" name="" txtTupa" cols="10" rows="2" readonly>@ViewData["iProced"]</textarea>
                                            </div>
                                            <div class="col-sm-2">
                                                <button type="button" class="btn btn-success pull-right" id="BTNBUSCART" name="BTNBUSCART" data-toggle="modal" data-target="#myModal"> <i class="icon-search"></i> Buscar Tupa</button>

                                            </div>
                                        </div>
                                        <div class="row" id="DivRequisito" style="display:none;">
                                            <div class="col-md-12">
                                                <div class="widget box">
                                                    <div class="widget-header">
                                                        <h4><i class="icon-table"></i>Listado de Requisitos Tupa</h4>

                                                    </div>
                                                    <div class="widget-content no-padding">
                                                        <table id="MGridR" class="table table-bordered table-hover table-checkable table-responsive datatable" width="100%">
                                                            @*class="table table-striped table-bordered" cellspacing="0"*@
                                                            <thead>
                                                                <tr>
                                                                    @*<th>Item</th>*@
                                                                    <th>Descripción del Procedimiento</th>
                                                                </tr>
                                                            </thead>

                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                    </div>




                                </div>
                            </div>


                            <div class="form-actions">

                                <input type="hidden" id="HCodTupa" name="HCodTupa" class="form-control" autocomplete="off">

                                <button type="button" class="btn btn-inverse pull-right" id="BtnRegresar" name="BtnRegresar" onclick="location.href='@Url.Action("Index", "Solicitud")'">
                                    <i class="icon-file-text-alt"></i> Regresar
                                </button>


                                <button type="button" class="btn btn-primary pull-right" id="BtnEnviar" name="BtnEnviar" onclick="FnConfirmaGuardar()">
                                    <i class="icon-file-text-alt"></i> Guardar Datos
                                </button>



                            </div>

                        </form>

                    </div>

              </div>
            </div>


        </div>

                <div class="row" id="Div02" style="display:none;">
                    <div class="col-md-10">
                        <div class="widget box">
                            <div class="widget-header">
                                <h4><i class="icon-reorder"></i> Registro de Expediente </h4>
                            </div>
                            <div class="widget-content">



                                <div class="row">

                                    <div class="col-md-4">
                                    </div>


                                    <div class="col-md-6">
                                        <div class="widget box">
                                            <div class="widget-header">
                                                <h4><i class="icon-reorder"></i> Resultado</h4>
                                            </div>
                                            <div class="widget-content align-center">
                                                <div class="alert alert-info fade in">

                                                    Se ha registrado Correctamente el Expediente
                                                </div>
                                              
                                                <center> <h2> <small id="H2NroSolicitud"></small></h2></center>
                                                <dl class="dl-horizontal">
                                                    <dt>Imprimir Solicitud: </dt>
                                                    <dd>Adjunte los archivos requeridos e imprime su constancia de la solicitud enviada.</dd>
                                                </dl>


                                                <button type="button" class="btn btn-default" id="BtnRegresar2" name="BtnRegresar2" onclick="location.href='@Url.Action("Index", "Solicitud")'">Regresar</button>

                                                </p>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="col-md-4">
                                    </div>


                                </div>


                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>

@Html.Partial("_SeleccionTupa")

<script src="~/Scripts/ScExpediente.js"></script>
<script src="~/Scripts/ScPublico.js"></script>

VentanillaVirtual.Web/Views/Expediente/RecepcionSEx.cshtml
@{
    ViewBag.Title = "RecepcionSEx";
    Layout = "~/Views/Shared/_Plantilla01.cshtml";
}


<div id="content">

    <div class="container">

        @Html.Partial("_MenuP02")

        <div class="row">
            <div class="col-md-12">
                <div class="widget box">
                    <div class="widget-content align-center">

                        <label class="control-label">Filtrar por Tipo de Busquedad </label>


                        <div class="alert alert-warning">

                            <label class="radio-inline">
                                <input type="radio" name="OptionRadio" value="Opt1" onclick="RadioSelect(this);"> Nro de Solicitud
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="OptionRadio" value="Opt2" onclick="RadioSelect(this);"> Administrado
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="OptionRadio" value="Opt3" onclick="RadioSelect(this);"> Fecha de envio
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="OptionRadio" value="Opt4" onclick="RadioSelect(this);" checked=""> Visualizar Todos
                            </label>

                        </div>


                        <table align="center">
                            <tr>
                                <td>
                                    <label class="col-md-12 control-label" id="LbSeleccionado">Default datepicker:</label>
                                </td>

                                <td>
                                    <input type="text" name="TxtBuscar" id="TxtBuscar" class="form-control input-width-large align-center">
                                </td>
                                <td>
                                    <input type="button" value="Buscar" class="btn btn-primary" id="BtnBuscar" name="BtnBuscar">
                                </td>
                            </tr>
                        </table>

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="widget box">
                    <div class="widget-header">
                        <h4><i class="icon-reorder"></i> </h4>

                    </div>
                    <div class="widget-content no-padding">

                        <table class="table table-striped table-bordered table-hover table-responsive datatable" id="DtSExpediente">

                            <thead>
                                <tr>
                                    <th data-class="expand">SOLICITUD</th>
                                    <th data-class="expand">FECHA ENVIO</th>
                                    <th data-class="expand">ADMINISTRADO</th>
                                    <th data-class="expand">ASUNTO</th>
                                    <th data-class="expand">FOLIOS</th>
                                    <th data-class="expand">ESTADO</th>
                                    <th data-class="expand">OPCIONES</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>

    </div>

</div>


@*@Html.Partial("_Adjuntar")*@

@Html.Partial("_VerSolicitud")

@Html.Partial("_Observacion")

@Html.Partial("_GenerarSid")

@Html.Partial("_GenerarPago")
@Html.Partial("_GenerarDatosPersona")

<script src="~/Scripts/ScRecepcionSEx.js"></script>

VentanillaVirtual.Web/Views/Expediente/RecepcionSExC.cshtml
@{
    ViewBag.Title = "RecepcionEXC";
    Layout = "~/Views/Shared/_Plantilla01.cshtml";
}

<div id="content">

    <div class="container">

        @Html.Partial("_MenuP02")

        <div class="row">
            <div class="col-md-12">
                <div class="widget box">
                    <div class="widget-content align-center">

                        <label class="control-label">Filtrar Registros por :  </label>

                        <input type="hidden" id="HCodRegi" name="HCodRegi" class="form-control" autocomplete="off" value="@ViewData["iIdRegi"]">

                        <div class="alert alert-warning">

                            <label class="radio-inline">
                                <input type="radio" name="OptionRadio" value="Opt1" onclick="RadioSelect(this);"> Nro de Solicitud
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="OptionRadio" value="Opt2" onclick="RadioSelect(this);"> Administrado
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="OptionRadio" value="Opt3" onclick="RadioSelect(this);"> Fecha de envio
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="OptionRadio" value="Opt4" onclick="RadioSelect(this);" checked=""> Visualizar Todos
                            </label>

                        </div>


                        <table align="center">
                            <tr>
                                <td>
                                    <label class="col-md-12 control-label" id="LbSeleccionado">:::</label>
                                </td>

                                <td>
                                    <input type="text" name="TxtBuscar" id="TxtBuscar" class="form-control input-width-large align-center">
                                </td>
                                <td>
                                    <input type="button" value="Buscar" class="btn btn-primary" id="BtnBuscar" name="BtnBuscar">
                                </td>
                            </tr>
                        </table>

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="widget box">
                    <div class="widget-header">
                        <h4><i class="icon-reorder"></i> </h4>

                    </div>
                    <div class="widget-content no-padding">

                        <table class="table table-striped table-bordered table-hover table-responsive datatable" id="DtSExpediente">

                            <thead>
                                <tr>
                                    <th data-class="expand">SOLICITUD</th>
                                    <th data-class="expand">EXPEDIENTE</th>
                                    <th data-class="expand">FEC. ENVIO</th>
                                    <th data-class="expand">ADMINISTRADO</th>
                                    <th data-class="expand">ASUNTO</th>
                                    <th data-class="expand">FOLIOS</th>
                                    <th data-class="expand">OBS</th>
                                    <th data-class="expand">ESTADO</th>
                                    <th data-class="expand">OPCIONES</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>

    </div>

</div>





@Html.Partial("_Adjuntar")

@Html.Partial("_Observacion")

@Html.Partial("_AdjuntarPago")


<script src="~/Scripts/ScRecepcionSExC.js"></script>